AddTileConfig /tile default
LoadTileConfigFile /etc/renderd.conf
ModTileRenderdSocketName /var/run/renderd/renderd.sock
ModTileRequestTimeout 0
ModTileMissingRequestTimeout 30
ModTileMaxLoadOld 16
ModTileMaxLoadMissing 50
ModTileEnableStats On
ModTileCacheDurationDirty 900
ModTileCacheDurationMinimum 10800
ModTileCacheDurationMediumZoom 12 86400
ModTileCacheDurationLowZoom 9 518400
