; BASIC AND SIMPLE CONFIGURATION:

[renderd]
socketname=/var/run/renderd/renderd.sock
num_threads=4
tile_dir=/var/lib/mod_tile

[mapnik]
plugins_dir=/usr/lib/x86_64-linux-gnu/mapnik/4.2/input
font_dir=/usr/share/fonts
font_dir_recurse=true

[default]
URI=/tile/
TILEDIR=/var/lib/mod_tile
XML=/home/sahil/openstreetmap-carto/mapnik.xml
HOST=localhost
TILESIZE=256
MAXZOOM=19

[india_osm]
URI=/osm_tiles/
XML=/home/sahil/mapserver/openstreetmap-carto/mapnik.xml
HOST=localhost
TILEDIR=/var/cache/renderd/tiles
MINZOOM=0
MAXZOOM=18
